require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ExpensetypesController do

  # This should return the minimal set of attributes required to create a valid
  # Expensetype. As you add validations to Expensetype, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ExpensetypesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all expensetypes as @expensetypes" do
      expensetype = Expensetype.create! valid_attributes
      get :index, {}, valid_session
      assigns(:expensetypes).should eq([expensetype])
    end
  end

  describe "GET show" do
    it "assigns the requested expensetype as @expensetype" do
      expensetype = Expensetype.create! valid_attributes
      get :show, {:id => expensetype.to_param}, valid_session
      assigns(:expensetype).should eq(expensetype)
    end
  end

  describe "GET new" do
    it "assigns a new expensetype as @expensetype" do
      get :new, {}, valid_session
      assigns(:expensetype).should be_a_new(Expensetype)
    end
  end

  describe "GET edit" do
    it "assigns the requested expensetype as @expensetype" do
      expensetype = Expensetype.create! valid_attributes
      get :edit, {:id => expensetype.to_param}, valid_session
      assigns(:expensetype).should eq(expensetype)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Expensetype" do
        expect {
          post :create, {:expensetype => valid_attributes}, valid_session
        }.to change(Expensetype, :count).by(1)
      end

      it "assigns a newly created expensetype as @expensetype" do
        post :create, {:expensetype => valid_attributes}, valid_session
        assigns(:expensetype).should be_a(Expensetype)
        assigns(:expensetype).should be_persisted
      end

      it "redirects to the created expensetype" do
        post :create, {:expensetype => valid_attributes}, valid_session
        response.should redirect_to(Expensetype.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved expensetype as @expensetype" do
        # Trigger the behavior that occurs when invalid params are submitted
        Expensetype.any_instance.stub(:save).and_return(false)
        post :create, {:expensetype => {}}, valid_session
        assigns(:expensetype).should be_a_new(Expensetype)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Expensetype.any_instance.stub(:save).and_return(false)
        post :create, {:expensetype => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested expensetype" do
        expensetype = Expensetype.create! valid_attributes
        # Assuming there are no other expensetypes in the database, this
        # specifies that the Expensetype created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Expensetype.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => expensetype.to_param, :expensetype => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested expensetype as @expensetype" do
        expensetype = Expensetype.create! valid_attributes
        put :update, {:id => expensetype.to_param, :expensetype => valid_attributes}, valid_session
        assigns(:expensetype).should eq(expensetype)
      end

      it "redirects to the expensetype" do
        expensetype = Expensetype.create! valid_attributes
        put :update, {:id => expensetype.to_param, :expensetype => valid_attributes}, valid_session
        response.should redirect_to(expensetype)
      end
    end

    describe "with invalid params" do
      it "assigns the expensetype as @expensetype" do
        expensetype = Expensetype.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Expensetype.any_instance.stub(:save).and_return(false)
        put :update, {:id => expensetype.to_param, :expensetype => {}}, valid_session
        assigns(:expensetype).should eq(expensetype)
      end

      it "re-renders the 'edit' template" do
        expensetype = Expensetype.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Expensetype.any_instance.stub(:save).and_return(false)
        put :update, {:id => expensetype.to_param, :expensetype => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested expensetype" do
      expensetype = Expensetype.create! valid_attributes
      expect {
        delete :destroy, {:id => expensetype.to_param}, valid_session
      }.to change(Expensetype, :count).by(-1)
    end

    it "redirects to the expensetypes list" do
      expensetype = Expensetype.create! valid_attributes
      delete :destroy, {:id => expensetype.to_param}, valid_session
      response.should redirect_to(expensetypes_url)
    end
  end

end
