require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TasktypesController do

  # This should return the minimal set of attributes required to create a valid
  # Tasktype. As you add validations to Tasktype, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TasktypesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all tasktypes as @tasktypes" do
      tasktype = Tasktype.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tasktypes).should eq([tasktype])
    end
  end

  describe "GET show" do
    it "assigns the requested tasktype as @tasktype" do
      tasktype = Tasktype.create! valid_attributes
      get :show, {:id => tasktype.to_param}, valid_session
      assigns(:tasktype).should eq(tasktype)
    end
  end

  describe "GET new" do
    it "assigns a new tasktype as @tasktype" do
      get :new, {}, valid_session
      assigns(:tasktype).should be_a_new(Tasktype)
    end
  end

  describe "GET edit" do
    it "assigns the requested tasktype as @tasktype" do
      tasktype = Tasktype.create! valid_attributes
      get :edit, {:id => tasktype.to_param}, valid_session
      assigns(:tasktype).should eq(tasktype)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tasktype" do
        expect {
          post :create, {:tasktype => valid_attributes}, valid_session
        }.to change(Tasktype, :count).by(1)
      end

      it "assigns a newly created tasktype as @tasktype" do
        post :create, {:tasktype => valid_attributes}, valid_session
        assigns(:tasktype).should be_a(Tasktype)
        assigns(:tasktype).should be_persisted
      end

      it "redirects to the created tasktype" do
        post :create, {:tasktype => valid_attributes}, valid_session
        response.should redirect_to(Tasktype.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tasktype as @tasktype" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tasktype.any_instance.stub(:save).and_return(false)
        post :create, {:tasktype => {}}, valid_session
        assigns(:tasktype).should be_a_new(Tasktype)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tasktype.any_instance.stub(:save).and_return(false)
        post :create, {:tasktype => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tasktype" do
        tasktype = Tasktype.create! valid_attributes
        # Assuming there are no other tasktypes in the database, this
        # specifies that the Tasktype created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tasktype.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => tasktype.to_param, :tasktype => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested tasktype as @tasktype" do
        tasktype = Tasktype.create! valid_attributes
        put :update, {:id => tasktype.to_param, :tasktype => valid_attributes}, valid_session
        assigns(:tasktype).should eq(tasktype)
      end

      it "redirects to the tasktype" do
        tasktype = Tasktype.create! valid_attributes
        put :update, {:id => tasktype.to_param, :tasktype => valid_attributes}, valid_session
        response.should redirect_to(tasktype)
      end
    end

    describe "with invalid params" do
      it "assigns the tasktype as @tasktype" do
        tasktype = Tasktype.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tasktype.any_instance.stub(:save).and_return(false)
        put :update, {:id => tasktype.to_param, :tasktype => {}}, valid_session
        assigns(:tasktype).should eq(tasktype)
      end

      it "re-renders the 'edit' template" do
        tasktype = Tasktype.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tasktype.any_instance.stub(:save).and_return(false)
        put :update, {:id => tasktype.to_param, :tasktype => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tasktype" do
      tasktype = Tasktype.create! valid_attributes
      expect {
        delete :destroy, {:id => tasktype.to_param}, valid_session
      }.to change(Tasktype, :count).by(-1)
    end

    it "redirects to the tasktypes list" do
      tasktype = Tasktype.create! valid_attributes
      delete :destroy, {:id => tasktype.to_param}, valid_session
      response.should redirect_to(tasktypes_url)
    end
  end

end
